meta_product_name: "{{ repo_name }}"
meta_title: "{{ repo_name }}"
meta_description: "{{ repo_name }}"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@your_twitter_account" # required for Twitter Cards